# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  backend:
    image: backend:latest
    container_name: Backend
    environment:
      - DBCONNECTIONSTRING=server=database;Database=Db;User=User;Password=1mW@tch1ngY0u;TreatTinyAsBoolean=true;Charset=utf8mb4;
    restart: always
    depends_on:
      - database

  frontend:
    container_name: Frontend
    image: frontend:latest
    environment:
      - NODE_ENV=development
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  database:
    image: mysql:latest
    container_name: Database
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    environment:
      - MYSQL_DATABASE=Db
      - MYSQL_USER=User
      - MYSQL_PASSWORD=1mW@tch1ngY0u
      - MYSQL_ROOT_PASSWORD=g00dLuckCr@ck!ngTh!s:)
    restart: always
